// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestApp.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AcessarPaginaFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "AcessarPagina.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt"), "Acessar Pagina", "\tEu como usuario do Sistema em escopo\r\n\tQuero acessar o sistema\r\n\tPara realizar m" +
                    "inha atividade qualquer", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Acessar Pagina")))
            {
                global::TestApp.Tests.Features.AcessarPaginaFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Acessar a home")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Acessar Pagina")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void AcessarAHome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acessar a home", new string[] {
                        "mytag"});
#line 10
 this.ScenarioSetup(scenarioInfo);
#line 11
  testRunner.Given("que eu estou na home do site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 12
  testRunner.Then("eu irei visualizar o texto \"Getting started\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 13
  testRunner.And("eu irei visualizar o texto \"Get more libraries\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
  testRunner.Then("Salvar evidência \"1.1.home.jpg\" em \"evidencias\\1\\\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Acessar a pagina de Contato")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Acessar Pagina")]
        public virtual void AcessarAPaginaDeContato()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Acessar a pagina de Contato", ((string[])(null)));
#line 16
 this.ScenarioSetup(scenarioInfo);
#line 17
  testRunner.Given("que eu estou na home do site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 18
  testRunner.Then("eu irei clicar no link \"Contact\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 19
  testRunner.Then("eu irei visualizar o texto \"Your contact page.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 20
  testRunner.And("eu irei visualizar o texto \"One Microsoft Way\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 21
  testRunner.Then("Salvar evidência \"1.2.contato.jpg\" em \"evidencias\\1\\\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
